-- 1. Create the projects table
create table public.projects (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  industry text not null,
  category text not null,
  description text not null,
  link text not null,
  image_url text
);

-- 2. Set up row level security (RLS)
alter table public.projects enable row level security;

-- Allow public read access to projects
create policy "Allow public read access"
  on public.projects for select
  using ( true );

-- Allow authenticated users (admins) to insert/update/delete projects
create policy "Allow authenticated users to insert projects"
  on public.projects for insert
  with check ( auth.role() = 'authenticated' );

create policy "Allow authenticated users to update projects"
  on public.projects for update
  using ( auth.role() = 'authenticated' );

create policy "Allow authenticated users to delete projects"
  on public.projects for delete
  using ( auth.role() = 'authenticated' );

-- 3. Create a storage bucket for project images
insert into storage.buckets (id, name, public) 
values ('portfolio', 'portfolio', true);

-- Allow public read access to storage
create policy "Public Access"
  on storage.objects for select
  using ( bucket_id = 'portfolio' );

-- Allow authenticated users to upload/update/delete images
create policy "Admin Upload Access"
  on storage.objects for insert
  with check ( bucket_id = 'portfolio' and auth.role() = 'authenticated' );

create policy "Admin Update Access"
  on storage.objects for update
  using ( bucket_id = 'portfolio' and auth.role() = 'authenticated' );

create policy "Admin Delete Access"
  on storage.objects for delete
  using ( bucket_id = 'portfolio' and auth.role() = 'authenticated' );
